server:
  port: 8081
  servlet-path: /rest/*
spring:
  application:
    name: decoration-manage
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://decoration:decoration@localhost:8761/eureka
  instance:
    prefer-ip-address: true